# Generated by Django 3.1.7 on 2021-03-23 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogdetailpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='intro',
            field=models.CharField(max_length=255, verbose_name='Introduction of the Post'),
        ),
    ]
